/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaIndexRouteImport } from './routes/empresa.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VerifyCredentialIdRouteImport } from './routes/verify.$credentialId'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as EmpresaVacantesRouteImport } from './routes/empresa.vacantes'
import { Route as EmpresaTalentoRouteImport } from './routes/empresa.talento'
import { Route as EmpresaTalentPoolRouteImport } from './routes/empresa.talent-pool'
import { Route as EmpresaRoiRouteImport } from './routes/empresa.roi'
import { Route as EmpresaFacturacionRouteImport } from './routes/empresa.facturacion'
import { Route as EmpresaEquipoRouteImport } from './routes/empresa.equipo'
import { Route as EmpresaEntrevistasRouteImport } from './routes/empresa.entrevistas'
import { Route as EmpresaDashboardRouteImport } from './routes/empresa.dashboard'
import { Route as EmpresaConfiguracionRouteImport } from './routes/empresa.configuracion'
import { Route as EmpresaAnaliticaRouteImport } from './routes/empresa.analitica'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'
import { Route as AppVerificacionRouteImport } from './routes/app.verificacion'
import { Route as AppVacantesRouteImport } from './routes/app.vacantes'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppPostulacionesRouteImport } from './routes/app.postulaciones'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacionesRouteImport } from './routes/app.notificaciones'
import { Route as AppMatchRouteImport } from './routes/app.match'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppEvaluacionesRouteImport } from './routes/app.evaluaciones'
import { Route as AppEntrevistasRouteImport } from './routes/app.entrevistas'
import { Route as AppEmpleabilidadRouteImport } from './routes/app.empleabilidad'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCvRouteImport } from './routes/app.cv'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppChallengesRouteImport } from './routes/app.challenges'
import { Route as AppCertificacionesRouteImport } from './routes/app.certificaciones'
import { Route as AppAprendizajeRouteImport } from './routes/app.aprendizaje'
import { Route as EmpresaVacantesIndexRouteImport } from './routes/empresa.vacantes.index'
import { Route as AppVacantesIndexRouteImport } from './routes/app.vacantes.index'
import { Route as AppPerfilIndexRouteImport } from './routes/app.perfil.index'
import { Route as AppEvaluacionesIndexRouteImport } from './routes/app.evaluaciones.index'
import { Route as AppCertificacionesIndexRouteImport } from './routes/app.certificaciones.index'
import { Route as EmpresaVacantesNuevaRouteImport } from './routes/empresa.vacantes.nueva'
import { Route as EmpresaVacantesIdRouteImport } from './routes/empresa.vacantes.$id'
import { Route as EmpresaCandidatosIdRouteImport } from './routes/empresa.candidatos.$id'
import { Route as AppVacantesIdRouteImport } from './routes/app.vacantes.$id'
import { Route as AppPerfilEditarRouteImport } from './routes/app.perfil.editar'
import { Route as AppEvaluacionesIdRouteImport } from './routes/app.evaluaciones.$id'
import { Route as AppCertificacionesCatalogoRouteImport } from './routes/app.certificaciones.catalogo'
import { Route as AppCertificacionesIdRouteImport } from './routes/app.certificaciones.$id'
import { Route as AppEvaluacionesIdIndexRouteImport } from './routes/app.evaluaciones.$id.index'
import { Route as AppEvaluacionesIdResultRouteImport } from './routes/app.evaluaciones.$id.result'

const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIndexRoute = EmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VerifyCredentialIdRoute = VerifyCredentialIdRouteImport.update({
  id: '/verify/$credentialId',
  path: '/verify/$credentialId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/legal/terminos',
  path: '/legal/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaVacantesRoute = EmpresaVacantesRouteImport.update({
  id: '/vacantes',
  path: '/vacantes',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaTalentoRoute = EmpresaTalentoRouteImport.update({
  id: '/talento',
  path: '/talento',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaTalentPoolRoute = EmpresaTalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaRoiRoute = EmpresaRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaFacturacionRoute = EmpresaFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaEquipoRoute = EmpresaEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaEntrevistasRoute = EmpresaEntrevistasRouteImport.update({
  id: '/entrevistas',
  path: '/entrevistas',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaDashboardRoute = EmpresaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaConfiguracionRoute = EmpresaConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaAnaliticaRoute = EmpresaAnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => EmpresaRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/auth/confirm-email',
  path: '/auth/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerificacionRoute = AppVerificacionRouteImport.update({
  id: '/verificacion',
  path: '/verificacion',
  getParentRoute: () => AppRoute,
} as any)
const AppVacantesRoute = AppVacantesRouteImport.update({
  id: '/vacantes',
  path: '/vacantes',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppPostulacionesRoute = AppPostulacionesRouteImport.update({
  id: '/postulaciones',
  path: '/postulaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluacionesRoute = AppEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrevistasRoute = AppEntrevistasRouteImport.update({
  id: '/entrevistas',
  path: '/entrevistas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleabilidadRoute = AppEmpleabilidadRouteImport.update({
  id: '/empleabilidad',
  path: '/empleabilidad',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCvRoute = AppCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificacionesRoute = AppCertificacionesRouteImport.update({
  id: '/certificaciones',
  path: '/certificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppAprendizajeRoute = AppAprendizajeRouteImport.update({
  id: '/aprendizaje',
  path: '/aprendizaje',
  getParentRoute: () => AppRoute,
} as any)
const EmpresaVacantesIndexRoute = EmpresaVacantesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaVacantesRoute,
} as any)
const AppVacantesIndexRoute = AppVacantesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVacantesRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppEvaluacionesIndexRoute = AppEvaluacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEvaluacionesRoute,
} as any)
const AppCertificacionesIndexRoute = AppCertificacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCertificacionesRoute,
} as any)
const EmpresaVacantesNuevaRoute = EmpresaVacantesNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => EmpresaVacantesRoute,
} as any)
const EmpresaVacantesIdRoute = EmpresaVacantesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresaVacantesRoute,
} as any)
const EmpresaCandidatosIdRoute = EmpresaCandidatosIdRouteImport.update({
  id: '/candidatos/$id',
  path: '/candidatos/$id',
  getParentRoute: () => EmpresaRoute,
} as any)
const AppVacantesIdRoute = AppVacantesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVacantesRoute,
} as any)
const AppPerfilEditarRoute = AppPerfilEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AppEvaluacionesIdRoute = AppEvaluacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEvaluacionesRoute,
} as any)
const AppCertificacionesCatalogoRoute =
  AppCertificacionesCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AppCertificacionesRoute,
  } as any)
const AppCertificacionesIdRoute = AppCertificacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCertificacionesRoute,
} as any)
const AppEvaluacionesIdIndexRoute = AppEvaluacionesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEvaluacionesIdRoute,
} as any)
const AppEvaluacionesIdResultRoute = AppEvaluacionesIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppEvaluacionesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/precios': typeof PreciosRoute
  '/app/aprendizaje': typeof AppAprendizajeRoute
  '/app/certificaciones': typeof AppCertificacionesRouteWithChildren
  '/app/challenges': typeof AppChallengesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/cv': typeof AppCvRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleabilidad': typeof AppEmpleabilidadRoute
  '/app/entrevistas': typeof AppEntrevistasRoute
  '/app/evaluaciones': typeof AppEvaluacionesRouteWithChildren
  '/app/learning': typeof AppLearningRoute
  '/app/match': typeof AppMatchRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/postulaciones': typeof AppPostulacionesRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/vacantes': typeof AppVacantesRouteWithChildren
  '/app/verificacion': typeof AppVerificacionRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/empresa/analitica': typeof EmpresaAnaliticaRoute
  '/empresa/configuracion': typeof EmpresaConfiguracionRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
  '/empresa/entrevistas': typeof EmpresaEntrevistasRoute
  '/empresa/equipo': typeof EmpresaEquipoRoute
  '/empresa/facturacion': typeof EmpresaFacturacionRoute
  '/empresa/roi': typeof EmpresaRoiRoute
  '/empresa/talent-pool': typeof EmpresaTalentPoolRoute
  '/empresa/talento': typeof EmpresaTalentoRoute
  '/empresa/vacantes': typeof EmpresaVacantesRouteWithChildren
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/app/': typeof AppIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/app/certificaciones/$id': typeof AppCertificacionesIdRoute
  '/app/certificaciones/catalogo': typeof AppCertificacionesCatalogoRoute
  '/app/evaluaciones/$id': typeof AppEvaluacionesIdRouteWithChildren
  '/app/perfil/editar': typeof AppPerfilEditarRoute
  '/app/vacantes/$id': typeof AppVacantesIdRoute
  '/empresa/candidatos/$id': typeof EmpresaCandidatosIdRoute
  '/empresa/vacantes/$id': typeof EmpresaVacantesIdRoute
  '/empresa/vacantes/nueva': typeof EmpresaVacantesNuevaRoute
  '/app/certificaciones/': typeof AppCertificacionesIndexRoute
  '/app/evaluaciones/': typeof AppEvaluacionesIndexRoute
  '/app/perfil/': typeof AppPerfilIndexRoute
  '/app/vacantes/': typeof AppVacantesIndexRoute
  '/empresa/vacantes/': typeof EmpresaVacantesIndexRoute
  '/app/evaluaciones/$id/result': typeof AppEvaluacionesIdResultRoute
  '/app/evaluaciones/$id/': typeof AppEvaluacionesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/precios': typeof PreciosRoute
  '/app/aprendizaje': typeof AppAprendizajeRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/cv': typeof AppCvRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleabilidad': typeof AppEmpleabilidadRoute
  '/app/entrevistas': typeof AppEntrevistasRoute
  '/app/learning': typeof AppLearningRoute
  '/app/match': typeof AppMatchRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/postulaciones': typeof AppPostulacionesRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/verificacion': typeof AppVerificacionRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/empresa/analitica': typeof EmpresaAnaliticaRoute
  '/empresa/configuracion': typeof EmpresaConfiguracionRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
  '/empresa/entrevistas': typeof EmpresaEntrevistasRoute
  '/empresa/equipo': typeof EmpresaEquipoRoute
  '/empresa/facturacion': typeof EmpresaFacturacionRoute
  '/empresa/roi': typeof EmpresaRoiRoute
  '/empresa/talent-pool': typeof EmpresaTalentPoolRoute
  '/empresa/talento': typeof EmpresaTalentoRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/app': typeof AppIndexRoute
  '/empresa': typeof EmpresaIndexRoute
  '/app/certificaciones/$id': typeof AppCertificacionesIdRoute
  '/app/certificaciones/catalogo': typeof AppCertificacionesCatalogoRoute
  '/app/perfil/editar': typeof AppPerfilEditarRoute
  '/app/vacantes/$id': typeof AppVacantesIdRoute
  '/empresa/candidatos/$id': typeof EmpresaCandidatosIdRoute
  '/empresa/vacantes/$id': typeof EmpresaVacantesIdRoute
  '/empresa/vacantes/nueva': typeof EmpresaVacantesNuevaRoute
  '/app/certificaciones': typeof AppCertificacionesIndexRoute
  '/app/evaluaciones': typeof AppEvaluacionesIndexRoute
  '/app/perfil': typeof AppPerfilIndexRoute
  '/app/vacantes': typeof AppVacantesIndexRoute
  '/empresa/vacantes': typeof EmpresaVacantesIndexRoute
  '/app/evaluaciones/$id/result': typeof AppEvaluacionesIdResultRoute
  '/app/evaluaciones/$id': typeof AppEvaluacionesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/precios': typeof PreciosRoute
  '/app/aprendizaje': typeof AppAprendizajeRoute
  '/app/certificaciones': typeof AppCertificacionesRouteWithChildren
  '/app/challenges': typeof AppChallengesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/cv': typeof AppCvRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleabilidad': typeof AppEmpleabilidadRoute
  '/app/entrevistas': typeof AppEntrevistasRoute
  '/app/evaluaciones': typeof AppEvaluacionesRouteWithChildren
  '/app/learning': typeof AppLearningRoute
  '/app/match': typeof AppMatchRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/postulaciones': typeof AppPostulacionesRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/vacantes': typeof AppVacantesRouteWithChildren
  '/app/verificacion': typeof AppVerificacionRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/empresa/analitica': typeof EmpresaAnaliticaRoute
  '/empresa/configuracion': typeof EmpresaConfiguracionRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
  '/empresa/entrevistas': typeof EmpresaEntrevistasRoute
  '/empresa/equipo': typeof EmpresaEquipoRoute
  '/empresa/facturacion': typeof EmpresaFacturacionRoute
  '/empresa/roi': typeof EmpresaRoiRoute
  '/empresa/talent-pool': typeof EmpresaTalentPoolRoute
  '/empresa/talento': typeof EmpresaTalentoRoute
  '/empresa/vacantes': typeof EmpresaVacantesRouteWithChildren
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/app/': typeof AppIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/app/certificaciones/$id': typeof AppCertificacionesIdRoute
  '/app/certificaciones/catalogo': typeof AppCertificacionesCatalogoRoute
  '/app/evaluaciones/$id': typeof AppEvaluacionesIdRouteWithChildren
  '/app/perfil/editar': typeof AppPerfilEditarRoute
  '/app/vacantes/$id': typeof AppVacantesIdRoute
  '/empresa/candidatos/$id': typeof EmpresaCandidatosIdRoute
  '/empresa/vacantes/$id': typeof EmpresaVacantesIdRoute
  '/empresa/vacantes/nueva': typeof EmpresaVacantesNuevaRoute
  '/app/certificaciones/': typeof AppCertificacionesIndexRoute
  '/app/evaluaciones/': typeof AppEvaluacionesIndexRoute
  '/app/perfil/': typeof AppPerfilIndexRoute
  '/app/vacantes/': typeof AppVacantesIndexRoute
  '/empresa/vacantes/': typeof EmpresaVacantesIndexRoute
  '/app/evaluaciones/$id/result': typeof AppEvaluacionesIdResultRoute
  '/app/evaluaciones/$id/': typeof AppEvaluacionesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/empresa'
    | '/precios'
    | '/app/aprendizaje'
    | '/app/certificaciones'
    | '/app/challenges'
    | '/app/configuracion'
    | '/app/cv'
    | '/app/dashboard'
    | '/app/empleabilidad'
    | '/app/entrevistas'
    | '/app/evaluaciones'
    | '/app/learning'
    | '/app/match'
    | '/app/notificaciones'
    | '/app/perfil'
    | '/app/postulaciones'
    | '/app/skills'
    | '/app/vacantes'
    | '/app/verificacion'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/empresa/analitica'
    | '/empresa/configuracion'
    | '/empresa/dashboard'
    | '/empresa/entrevistas'
    | '/empresa/equipo'
    | '/empresa/facturacion'
    | '/empresa/roi'
    | '/empresa/talent-pool'
    | '/empresa/talento'
    | '/empresa/vacantes'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/verify/$credentialId'
    | '/app/'
    | '/empresa/'
    | '/app/certificaciones/$id'
    | '/app/certificaciones/catalogo'
    | '/app/evaluaciones/$id'
    | '/app/perfil/editar'
    | '/app/vacantes/$id'
    | '/empresa/candidatos/$id'
    | '/empresa/vacantes/$id'
    | '/empresa/vacantes/nueva'
    | '/app/certificaciones/'
    | '/app/evaluaciones/'
    | '/app/perfil/'
    | '/app/vacantes/'
    | '/empresa/vacantes/'
    | '/app/evaluaciones/$id/result'
    | '/app/evaluaciones/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/precios'
    | '/app/aprendizaje'
    | '/app/challenges'
    | '/app/configuracion'
    | '/app/cv'
    | '/app/dashboard'
    | '/app/empleabilidad'
    | '/app/entrevistas'
    | '/app/learning'
    | '/app/match'
    | '/app/notificaciones'
    | '/app/postulaciones'
    | '/app/skills'
    | '/app/verificacion'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/empresa/analitica'
    | '/empresa/configuracion'
    | '/empresa/dashboard'
    | '/empresa/entrevistas'
    | '/empresa/equipo'
    | '/empresa/facturacion'
    | '/empresa/roi'
    | '/empresa/talent-pool'
    | '/empresa/talento'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/verify/$credentialId'
    | '/app'
    | '/empresa'
    | '/app/certificaciones/$id'
    | '/app/certificaciones/catalogo'
    | '/app/perfil/editar'
    | '/app/vacantes/$id'
    | '/empresa/candidatos/$id'
    | '/empresa/vacantes/$id'
    | '/empresa/vacantes/nueva'
    | '/app/certificaciones'
    | '/app/evaluaciones'
    | '/app/perfil'
    | '/app/vacantes'
    | '/empresa/vacantes'
    | '/app/evaluaciones/$id/result'
    | '/app/evaluaciones/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/empresa'
    | '/precios'
    | '/app/aprendizaje'
    | '/app/certificaciones'
    | '/app/challenges'
    | '/app/configuracion'
    | '/app/cv'
    | '/app/dashboard'
    | '/app/empleabilidad'
    | '/app/entrevistas'
    | '/app/evaluaciones'
    | '/app/learning'
    | '/app/match'
    | '/app/notificaciones'
    | '/app/perfil'
    | '/app/postulaciones'
    | '/app/skills'
    | '/app/vacantes'
    | '/app/verificacion'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/empresa/analitica'
    | '/empresa/configuracion'
    | '/empresa/dashboard'
    | '/empresa/entrevistas'
    | '/empresa/equipo'
    | '/empresa/facturacion'
    | '/empresa/roi'
    | '/empresa/talent-pool'
    | '/empresa/talento'
    | '/empresa/vacantes'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/verify/$credentialId'
    | '/app/'
    | '/empresa/'
    | '/app/certificaciones/$id'
    | '/app/certificaciones/catalogo'
    | '/app/evaluaciones/$id'
    | '/app/perfil/editar'
    | '/app/vacantes/$id'
    | '/empresa/candidatos/$id'
    | '/empresa/vacantes/$id'
    | '/empresa/vacantes/nueva'
    | '/app/certificaciones/'
    | '/app/evaluaciones/'
    | '/app/perfil/'
    | '/app/vacantes/'
    | '/empresa/vacantes/'
    | '/app/evaluaciones/$id/result'
    | '/app/evaluaciones/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EmpresaRoute: typeof EmpresaRouteWithChildren
  PreciosRoute: typeof PreciosRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
  VerifyCredentialIdRoute: typeof VerifyCredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/': {
      id: '/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof EmpresaIndexRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$credentialId': {
      id: '/verify/$credentialId'
      path: '/verify/$credentialId'
      fullPath: '/verify/$credentialId'
      preLoaderRoute: typeof VerifyCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/legal/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/vacantes': {
      id: '/empresa/vacantes'
      path: '/vacantes'
      fullPath: '/empresa/vacantes'
      preLoaderRoute: typeof EmpresaVacantesRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/talento': {
      id: '/empresa/talento'
      path: '/talento'
      fullPath: '/empresa/talento'
      preLoaderRoute: typeof EmpresaTalentoRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/talent-pool': {
      id: '/empresa/talent-pool'
      path: '/talent-pool'
      fullPath: '/empresa/talent-pool'
      preLoaderRoute: typeof EmpresaTalentPoolRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/roi': {
      id: '/empresa/roi'
      path: '/roi'
      fullPath: '/empresa/roi'
      preLoaderRoute: typeof EmpresaRoiRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/facturacion': {
      id: '/empresa/facturacion'
      path: '/facturacion'
      fullPath: '/empresa/facturacion'
      preLoaderRoute: typeof EmpresaFacturacionRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/equipo': {
      id: '/empresa/equipo'
      path: '/equipo'
      fullPath: '/empresa/equipo'
      preLoaderRoute: typeof EmpresaEquipoRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/entrevistas': {
      id: '/empresa/entrevistas'
      path: '/entrevistas'
      fullPath: '/empresa/entrevistas'
      preLoaderRoute: typeof EmpresaEntrevistasRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/dashboard': {
      id: '/empresa/dashboard'
      path: '/dashboard'
      fullPath: '/empresa/dashboard'
      preLoaderRoute: typeof EmpresaDashboardRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/configuracion': {
      id: '/empresa/configuracion'
      path: '/configuracion'
      fullPath: '/empresa/configuracion'
      preLoaderRoute: typeof EmpresaConfiguracionRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/analitica': {
      id: '/empresa/analitica'
      path: '/analitica'
      fullPath: '/empresa/analitica'
      preLoaderRoute: typeof EmpresaAnaliticaRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/auth/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verificacion': {
      id: '/app/verificacion'
      path: '/verificacion'
      fullPath: '/app/verificacion'
      preLoaderRoute: typeof AppVerificacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacantes': {
      id: '/app/vacantes'
      path: '/vacantes'
      fullPath: '/app/vacantes'
      preLoaderRoute: typeof AppVacantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/postulaciones': {
      id: '/app/postulaciones'
      path: '/postulaciones'
      fullPath: '/app/postulaciones'
      preLoaderRoute: typeof AppPostulacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificaciones': {
      id: '/app/notificaciones'
      path: '/notificaciones'
      fullPath: '/app/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluaciones': {
      id: '/app/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/app/evaluaciones'
      preLoaderRoute: typeof AppEvaluacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrevistas': {
      id: '/app/entrevistas'
      path: '/entrevistas'
      fullPath: '/app/entrevistas'
      preLoaderRoute: typeof AppEntrevistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empleabilidad': {
      id: '/app/empleabilidad'
      path: '/empleabilidad'
      fullPath: '/app/empleabilidad'
      preLoaderRoute: typeof AppEmpleabilidadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cv': {
      id: '/app/cv'
      path: '/cv'
      fullPath: '/app/cv'
      preLoaderRoute: typeof AppCvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/challenges': {
      id: '/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificaciones': {
      id: '/app/certificaciones'
      path: '/certificaciones'
      fullPath: '/app/certificaciones'
      preLoaderRoute: typeof AppCertificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprendizaje': {
      id: '/app/aprendizaje'
      path: '/aprendizaje'
      fullPath: '/app/aprendizaje'
      preLoaderRoute: typeof AppAprendizajeRouteImport
      parentRoute: typeof AppRoute
    }
    '/empresa/vacantes/': {
      id: '/empresa/vacantes/'
      path: '/'
      fullPath: '/empresa/vacantes/'
      preLoaderRoute: typeof EmpresaVacantesIndexRouteImport
      parentRoute: typeof EmpresaVacantesRoute
    }
    '/app/vacantes/': {
      id: '/app/vacantes/'
      path: '/'
      fullPath: '/app/vacantes/'
      preLoaderRoute: typeof AppVacantesIndexRouteImport
      parentRoute: typeof AppVacantesRoute
    }
    '/app/perfil/': {
      id: '/app/perfil/'
      path: '/'
      fullPath: '/app/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/evaluaciones/': {
      id: '/app/evaluaciones/'
      path: '/'
      fullPath: '/app/evaluaciones/'
      preLoaderRoute: typeof AppEvaluacionesIndexRouteImport
      parentRoute: typeof AppEvaluacionesRoute
    }
    '/app/certificaciones/': {
      id: '/app/certificaciones/'
      path: '/'
      fullPath: '/app/certificaciones/'
      preLoaderRoute: typeof AppCertificacionesIndexRouteImport
      parentRoute: typeof AppCertificacionesRoute
    }
    '/empresa/vacantes/nueva': {
      id: '/empresa/vacantes/nueva'
      path: '/nueva'
      fullPath: '/empresa/vacantes/nueva'
      preLoaderRoute: typeof EmpresaVacantesNuevaRouteImport
      parentRoute: typeof EmpresaVacantesRoute
    }
    '/empresa/vacantes/$id': {
      id: '/empresa/vacantes/$id'
      path: '/$id'
      fullPath: '/empresa/vacantes/$id'
      preLoaderRoute: typeof EmpresaVacantesIdRouteImport
      parentRoute: typeof EmpresaVacantesRoute
    }
    '/empresa/candidatos/$id': {
      id: '/empresa/candidatos/$id'
      path: '/candidatos/$id'
      fullPath: '/empresa/candidatos/$id'
      preLoaderRoute: typeof EmpresaCandidatosIdRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/app/vacantes/$id': {
      id: '/app/vacantes/$id'
      path: '/$id'
      fullPath: '/app/vacantes/$id'
      preLoaderRoute: typeof AppVacantesIdRouteImport
      parentRoute: typeof AppVacantesRoute
    }
    '/app/perfil/editar': {
      id: '/app/perfil/editar'
      path: '/editar'
      fullPath: '/app/perfil/editar'
      preLoaderRoute: typeof AppPerfilEditarRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/app/evaluaciones/$id': {
      id: '/app/evaluaciones/$id'
      path: '/$id'
      fullPath: '/app/evaluaciones/$id'
      preLoaderRoute: typeof AppEvaluacionesIdRouteImport
      parentRoute: typeof AppEvaluacionesRoute
    }
    '/app/certificaciones/catalogo': {
      id: '/app/certificaciones/catalogo'
      path: '/catalogo'
      fullPath: '/app/certificaciones/catalogo'
      preLoaderRoute: typeof AppCertificacionesCatalogoRouteImport
      parentRoute: typeof AppCertificacionesRoute
    }
    '/app/certificaciones/$id': {
      id: '/app/certificaciones/$id'
      path: '/$id'
      fullPath: '/app/certificaciones/$id'
      preLoaderRoute: typeof AppCertificacionesIdRouteImport
      parentRoute: typeof AppCertificacionesRoute
    }
    '/app/evaluaciones/$id/': {
      id: '/app/evaluaciones/$id/'
      path: '/'
      fullPath: '/app/evaluaciones/$id/'
      preLoaderRoute: typeof AppEvaluacionesIdIndexRouteImport
      parentRoute: typeof AppEvaluacionesIdRoute
    }
    '/app/evaluaciones/$id/result': {
      id: '/app/evaluaciones/$id/result'
      path: '/result'
      fullPath: '/app/evaluaciones/$id/result'
      preLoaderRoute: typeof AppEvaluacionesIdResultRouteImport
      parentRoute: typeof AppEvaluacionesIdRoute
    }
  }
}

interface AppCertificacionesRouteChildren {
  AppCertificacionesIdRoute: typeof AppCertificacionesIdRoute
  AppCertificacionesCatalogoRoute: typeof AppCertificacionesCatalogoRoute
  AppCertificacionesIndexRoute: typeof AppCertificacionesIndexRoute
}

const AppCertificacionesRouteChildren: AppCertificacionesRouteChildren = {
  AppCertificacionesIdRoute: AppCertificacionesIdRoute,
  AppCertificacionesCatalogoRoute: AppCertificacionesCatalogoRoute,
  AppCertificacionesIndexRoute: AppCertificacionesIndexRoute,
}

const AppCertificacionesRouteWithChildren =
  AppCertificacionesRoute._addFileChildren(AppCertificacionesRouteChildren)

interface AppEvaluacionesIdRouteChildren {
  AppEvaluacionesIdResultRoute: typeof AppEvaluacionesIdResultRoute
  AppEvaluacionesIdIndexRoute: typeof AppEvaluacionesIdIndexRoute
}

const AppEvaluacionesIdRouteChildren: AppEvaluacionesIdRouteChildren = {
  AppEvaluacionesIdResultRoute: AppEvaluacionesIdResultRoute,
  AppEvaluacionesIdIndexRoute: AppEvaluacionesIdIndexRoute,
}

const AppEvaluacionesIdRouteWithChildren =
  AppEvaluacionesIdRoute._addFileChildren(AppEvaluacionesIdRouteChildren)

interface AppEvaluacionesRouteChildren {
  AppEvaluacionesIdRoute: typeof AppEvaluacionesIdRouteWithChildren
  AppEvaluacionesIndexRoute: typeof AppEvaluacionesIndexRoute
}

const AppEvaluacionesRouteChildren: AppEvaluacionesRouteChildren = {
  AppEvaluacionesIdRoute: AppEvaluacionesIdRouteWithChildren,
  AppEvaluacionesIndexRoute: AppEvaluacionesIndexRoute,
}

const AppEvaluacionesRouteWithChildren = AppEvaluacionesRoute._addFileChildren(
  AppEvaluacionesRouteChildren,
)

interface AppPerfilRouteChildren {
  AppPerfilEditarRoute: typeof AppPerfilEditarRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
}

const AppPerfilRouteChildren: AppPerfilRouteChildren = {
  AppPerfilEditarRoute: AppPerfilEditarRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
}

const AppPerfilRouteWithChildren = AppPerfilRoute._addFileChildren(
  AppPerfilRouteChildren,
)

interface AppVacantesRouteChildren {
  AppVacantesIdRoute: typeof AppVacantesIdRoute
  AppVacantesIndexRoute: typeof AppVacantesIndexRoute
}

const AppVacantesRouteChildren: AppVacantesRouteChildren = {
  AppVacantesIdRoute: AppVacantesIdRoute,
  AppVacantesIndexRoute: AppVacantesIndexRoute,
}

const AppVacantesRouteWithChildren = AppVacantesRoute._addFileChildren(
  AppVacantesRouteChildren,
)

interface AppRouteChildren {
  AppAprendizajeRoute: typeof AppAprendizajeRoute
  AppCertificacionesRoute: typeof AppCertificacionesRouteWithChildren
  AppChallengesRoute: typeof AppChallengesRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppCvRoute: typeof AppCvRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpleabilidadRoute: typeof AppEmpleabilidadRoute
  AppEntrevistasRoute: typeof AppEntrevistasRoute
  AppEvaluacionesRoute: typeof AppEvaluacionesRouteWithChildren
  AppLearningRoute: typeof AppLearningRoute
  AppMatchRoute: typeof AppMatchRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPerfilRoute: typeof AppPerfilRouteWithChildren
  AppPostulacionesRoute: typeof AppPostulacionesRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppVacantesRoute: typeof AppVacantesRouteWithChildren
  AppVerificacionRoute: typeof AppVerificacionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprendizajeRoute: AppAprendizajeRoute,
  AppCertificacionesRoute: AppCertificacionesRouteWithChildren,
  AppChallengesRoute: AppChallengesRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppCvRoute: AppCvRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpleabilidadRoute: AppEmpleabilidadRoute,
  AppEntrevistasRoute: AppEntrevistasRoute,
  AppEvaluacionesRoute: AppEvaluacionesRouteWithChildren,
  AppLearningRoute: AppLearningRoute,
  AppMatchRoute: AppMatchRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPerfilRoute: AppPerfilRouteWithChildren,
  AppPostulacionesRoute: AppPostulacionesRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppVacantesRoute: AppVacantesRouteWithChildren,
  AppVerificacionRoute: AppVerificacionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface EmpresaVacantesRouteChildren {
  EmpresaVacantesIdRoute: typeof EmpresaVacantesIdRoute
  EmpresaVacantesNuevaRoute: typeof EmpresaVacantesNuevaRoute
  EmpresaVacantesIndexRoute: typeof EmpresaVacantesIndexRoute
}

const EmpresaVacantesRouteChildren: EmpresaVacantesRouteChildren = {
  EmpresaVacantesIdRoute: EmpresaVacantesIdRoute,
  EmpresaVacantesNuevaRoute: EmpresaVacantesNuevaRoute,
  EmpresaVacantesIndexRoute: EmpresaVacantesIndexRoute,
}

const EmpresaVacantesRouteWithChildren = EmpresaVacantesRoute._addFileChildren(
  EmpresaVacantesRouteChildren,
)

interface EmpresaRouteChildren {
  EmpresaAnaliticaRoute: typeof EmpresaAnaliticaRoute
  EmpresaConfiguracionRoute: typeof EmpresaConfiguracionRoute
  EmpresaDashboardRoute: typeof EmpresaDashboardRoute
  EmpresaEntrevistasRoute: typeof EmpresaEntrevistasRoute
  EmpresaEquipoRoute: typeof EmpresaEquipoRoute
  EmpresaFacturacionRoute: typeof EmpresaFacturacionRoute
  EmpresaRoiRoute: typeof EmpresaRoiRoute
  EmpresaTalentPoolRoute: typeof EmpresaTalentPoolRoute
  EmpresaTalentoRoute: typeof EmpresaTalentoRoute
  EmpresaVacantesRoute: typeof EmpresaVacantesRouteWithChildren
  EmpresaIndexRoute: typeof EmpresaIndexRoute
  EmpresaCandidatosIdRoute: typeof EmpresaCandidatosIdRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaAnaliticaRoute: EmpresaAnaliticaRoute,
  EmpresaConfiguracionRoute: EmpresaConfiguracionRoute,
  EmpresaDashboardRoute: EmpresaDashboardRoute,
  EmpresaEntrevistasRoute: EmpresaEntrevistasRoute,
  EmpresaEquipoRoute: EmpresaEquipoRoute,
  EmpresaFacturacionRoute: EmpresaFacturacionRoute,
  EmpresaRoiRoute: EmpresaRoiRoute,
  EmpresaTalentPoolRoute: EmpresaTalentPoolRoute,
  EmpresaTalentoRoute: EmpresaTalentoRoute,
  EmpresaVacantesRoute: EmpresaVacantesRouteWithChildren,
  EmpresaIndexRoute: EmpresaIndexRoute,
  EmpresaCandidatosIdRoute: EmpresaCandidatosIdRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EmpresaRoute: EmpresaRouteWithChildren,
  PreciosRoute: PreciosRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
  VerifyCredentialIdRoute: VerifyCredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
